#!/usr/bin/bash


set -e


source 'install-scripts/common/ui'
source 'install-scripts/qemu/partition'
source 'install-scripts/qemu/basesys'


disk='/dev/vda'
msg "No system password for virtual machines"

msg "Configure network"
systemctl start dhcpcd.service

msg "Check network availability"
if ! wait_network 10 ; then
    error "Cannot setup network connection"
fi

msg "Prepare partitions"
prepare_partitions "$disk" swap root

msg "Format partitions"
format_partitions "$swap" "$root"

msg "Check partitions"
check_partitions

msg "Pacstrap base system"
pacstrap_base_system

msg "Setup system boot"
setup_system_boot "$disk"

msg "Setup system network"
setup_system_network

msg "Setup system auto-install"
setup_system_autoinstall


poweroff
