#!/usr/bin/bash


set -e


source 'install-scripts/common/network'
source 'install-scripts/common/ui'
source 'install-scripts/qemu/basesys'


add_package_repo() {
    local conf="$1" ; shift

    {
	printf '\n[mnesic]\n'
	printf 'SigLevel = Optional TrustAll\n'
	printf 'Server = http://www.mnesic.fr/files/archlinux/$repo/$arch'
    } >> "$conf"
}

create_pacman_conf() {
    conf="$(mktemp --tmpdir --suffix='.conf' 'pacman.XXXXXXXXXX')"
    cp '/etc/pacman.conf' "$conf"

    add_package_repo "$conf"

    sed -ri 's/^#Color/Color/' "$conf"

    echo "$conf"
}

setup_users() {
    useradd --gid users --groups sudo --create-home --no-user-group \
	    --shell '/usr/bin/zsh' 'gauthier'

    passwd -d 'gauthier'
    passwd -l 'root'
}


msg "Create custom pacman configuration"
pconf="`create_pacman_conf`"

msg "Check network availability"
if ! wait_network 10 ; then
    error "Cannot setup network connection"
fi

msg "Install full system"
pacman -Sy --config "$pconf" --noconfirm config-qemu

msg "Update pacman configuration"
add_package_repo '/etc/pacman.conf'

msg "Setup groups and users"
setup_users

msg "Finish installation"
remove_system_autoinstall

msg "Setup autologin"
systemctl disable getty@tty1
systemctl enable autologin@gauthier

msg "Run file indexing"
updatedb

msg "Reboot system"
reboot
