#!/usr/bin/bash


COMMAND_LIST=()


add_chroot_commands() {
    for cmd in "$@" ; do
	COMMAND_LIST+=("$cmd")
    done
}

execute_chroot_command() {
    local ret
    local already

    {
	printf '#!/usr/bin/bash\n'
	echo
	printf "cd '/root'\n"
	echo
	printf "source 'install-scripts/common/temp'\n"
	printf "source 'install-scripts/common/ui'\n"
	echo

	for cmd in "${COMMAND_LIST[@]}" ; do
	    printf '%s\n' "$cmd"
	done
    } > '/mnt/root/chroot-script'

    chmod 700 '/mnt/root/chroot-script'

    if [ -e '/mnt/root/install-scripts' ] ; then
	already=1
    else
	already=0
	cp -R 'install-scripts' '/mnt/root/install-scripts'
    fi

    if arch-chroot '/mnt' '/root/chroot-script' ; then
	ret=0
    else
	ret=1
    fi

    rm -rf '/mnt/root/chroot-script'

    if [ $already -eq  0 ] ; then
	rm -rf '/mnt/root/install-scripts'
    fi

    COMMAND_LIST=()

    return $ret
}
