#!/usr/bin/bash

if [ "x$SOURCED_COMMON_TEMP" = 'x' ] ; then
SOURCE_COMMON_TEMP=1


CLEAN_LIST=()


# cleanup
# Remove all the files added to the autoclean list with autoclean().
# Clear the autoclean list after that.
cleanup() {
    for path in "${CLEAN_LIST[@]}" ; do
	rm -rf "$path" 2> /dev/null
    done

    CLEAN_LIST=()

    return 0
}

# autoclean <paths...>
# Add paths to the autoclean list.
# When the cleanup() function is invoked, all the files on the autoclean list
# are removed.
autoclean() {
    for path in "$@" ; do
	CLEAN_LIST+="$path"
    done
}


fi
