#!/usr/bin/bash


set -e


source 'install-scripts/common/ui'
source 'install-scripts/bouleau/partition'
source 'install-scripts/bouleau/basesys'


msg "Set keyboard layout"

disk='/dev/sda'

ask_help none "Configure network"

msg "Prepare partitions"
prepare_partitions "$disk" swap root home

msg "Format partitions"
format_partitions "$swap" "$root" "$home"

msg "Check partitions"
check_partitions

msg "Pacstrap base system"
pacstrap_base_system

msg "Setup system boot"
setup_system_boot "$disk" "$crypt"

msg "Setup system network"
setup_system_network

msg "Setup system auto-install"
setup_system_autoinstall


reboot
