#!/usr/bin/bash


set -e


source 'script/common/ui'
source 'script/laurier/partition'
source 'script/laurier/basesys'


msg "Set large font"
setfont 'ter-132n'

disk='/dev/nvme0n1'
ask_password passwd "Enter system password"

ask_help none "Configure network"

msg "Prepare partitions"
prepare_partitions "$disk" "$passwd" crypt boot swap root home

msg "Format partitions"
format_partitions "$boot" "$swap" "$root" "$home"

msg "Check partitions"
check_partitions

msg "Pacstrap base system"
pacstrap_base_system

msg "Setup system boot"
setup_system_boot "$disk" "$crypt"

msg "Setup system network"
setup_system_network

msg "Setup system auto-install"
setup_system_autoinstall "$passwd"


reboot
