#!/usr/bin/bash


source 'install-scripts/common/chroot'
source 'install-scripts/common/network'
source 'install-scripts/common/pacman'
source 'install-scripts/common/temp'
source 'install-scripts/common/ui'


pacstrap_base_system() {
    info 'Install base packages'
    pacstrap '/mnt' 'base' 'dhcpcd' 'dialog' 'grub' 'efibootmgr'    \
	     'intel-ucode' 'linux' 'linux-firmware' 'lvm2' 'netctl' \
	     'wpa_supplicant'

    info 'Bind base packages'
    bind_system_packages
}

setup_system_boot() {
    local disk="$1" ; shift
    local cryptpart="$1" ; shift
    local cryptuuid=$(lsblk -nldo UUID "$cryptpart")
    local entry usbentry

    info "Generate '/etc/fstab'"
    genfstab -U '/mnt' >> '/mnt/etc/fstab'

    info "Add encryption hook to initramfs"
    sed -ri 's/HOOKS=(.*) keyboard(.*)/HOOKS=\1\2/' '/mnt/etc/mkinitcpio.conf'
    sed -ri 's/HOOKS=(.*) filesystems(.*)/HOOKS=\1 keyboard encrypt lvm2 filesystems\2/' '/mnt/etc/mkinitcpio.conf'
    add_chroot_commands "mkinitcpio -p linux"
    
    info "Add encryption support to GRUB"
    sed -ri 's!GRUB_CMDLINE_LINUX="(.*)!GRUB_CMDLINE_LINUX="cryptdevice=UUID='"$cryptuuid"':lvm root=/dev/system/root \1!' \
	'/mnt/etc/default/grub'

    info "Set custom video mode for GRUB"
    sed -ri 's/GRUB_GFXMODE=auto/GRUB_GFXMODE=1600x1200x32,auto/' \
	'/mnt/etc/default/grub'

    info "Set custom timeout for GRUB"
    sed -ri 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=2/' '/mnt/etc/default/grub'

    info "Install grub on boot disk '$disk'"
    add_chroot_commands "grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub --no-nvram"
    add_chroot_commands "grub-mkconfig -o /boot/grub/grub.cfg"

    info 'Execute chrooted update'
    execute_chroot_command

    info "Remove old UEFI boot entry"
    usbentry=`efibootmgr | sed -nr 's/BootCurrent: ([[:digit:]]{4})$/\1/p'`
    for entry in `efibootmgr | sed -nr 's/^Boot([[:digit:]]{4}).*$/\1/p'` ; do
	if [ "$entry" = "$usbentry" ] ; then
	    continue
	fi
	efibootmgr --bootnum "$entry" --delete-bootnum
    done

    info "Setup grub UEFI boot entry"
    efibootmgr --create --disk "$disk" --part 1 \
	       --loader '/EFI/grub/grubx64.efi' --label 'UEFI : System Disk'
}

setup_system_network() {
    info "Setup netctl"
    setup_netctl
}

setup_system_autoinstall() {
    local passwd="$1" ; shift

    info 'Copy install scripts'
    cp -R '/root/install-scripts' '/mnt/root/install-scripts'

    info 'Configure install autologin'
    sed -r 's!^ExecStart=.*!ExecStart=-/sbin/agetty --noclear -a root %I 38400 linux!' \
	'/mnt/usr/lib/systemd/system/getty@.service' \
	> '/mnt/usr/lib/systemd/system/install-autologin@.service'

    add_chroot_commands "systemctl disable getty@tty1"
    add_chroot_commands "systemctl enable install-autologin@tty1"
    execute_chroot_command

    info 'Configure install autolaunch'
    {
	printf '#!/usr/bin/bash\n'
	echo
	printf "./install-scripts/laurier/stage-2 '%s'\n" "$passwd"
    } > '/mnt/root/.profile'
}

remove_system_autoinstall() {
    info 'Deconfigure autologin'
    systemctl disable install-autologin@tty1
    systemctl enable getty@tty1

    info 'Deconfigure install autolaunch'
    rm '.profile'
    rm '/usr/lib/systemd/system/install-autologin@.service'

    info 'Delete install scripts'
    rm -rf '/root/install-scripts'
}
